name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        apk add build-base git zip

    - name: Configure Git Safe Directory
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Compile project
      run: |
        make all --trace

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: SMS-${{ steps.slug.outputs.sha8 }}
        path: bin/SMS.elf
